<div class="header__top__menu-box col-mobile-12 col-tablet-6">
    <ul class="header__menu-link">
        <li>
            <a href="#"><span>Wishlist(o)</span></a>
        </li>
        <li>
            <a href="#"><span>Compare(o)</span></a>
        </li>
        <li class="last-child">
            <a href="#" class="btn-current">
                <i class="fa icon-arrow-down"></i><span>Account</span>
            </a>
            <!-- <ul class="dropdown-menu">
                <li><a href="#">Log in</a></li>
                <li><a href="#">Register</a></li>
            </ul> -->
        </li>
    </ul>
</div>