<div class="footer__info-box">
    <div class="container">
        <div class="item item1 col-mobile-12 col-desktop-6 col-laptop-3">
            <a href="#"><img class="logo-footer" src="<?=$block->getViewFileUrl("images/logo-footer.png");?>" alt=""></a>
            <p>Vestibulum sagittis, nisl nec pellentesque suscipit, arcu nisi maximus neque, vitae finibus erat odio eu lacus. Curabitur malesuada erat eros, quis dignissim dui accumsan id. Cras non imperdiet metus.</p>
            <a href="#" class="continue">Continus Reading >></a>
        </div>
        <div class="item item2 col-mobile-12 col-desktop-6 col-laptop-3">
            <h4>Customer service</h4>
            <ul class="list-link-footer">
                <li><a href="">Shipping Policy</a></li>
                <li><a href="">Compensation Fist</a></li>
                <li><a href="">My Account</a></li>
                <li><a href="">Return Policy</a></li>
                <li><a href="">Contact Us</a></li>
            </ul>
        </div>
        <div class="item item3 col-mobile-12 col-desktop-6 col-laptop-3">
            <h4>Payment & Shipping</h4>
            <ul class="list-link-footer">
                <li><a href="">Term of Use</a></li>
                <li><a href="">Payment Methods</a></li>
                <li><a href="">Shipping Guide</a></li>
                <li><a href="">Locations We Ship To</a></li>
                <li><a href="">Estimated Delivery Time</a></li>
            </ul>
        </div>
        <div class="item item4 col-mobile-12 col-desktop-6 col-laptop-3">
            <h4>Contact us</h4>
            <ul class="list-link-footer">
                <li class="address">
                    <i class="fa icon-address"></i><strong><label>address: </label></strong> <span>Lorem ipsum dolor sit amet, Onsectetuer adipiscing elit.</span>
                </li>
                <li class="email">
                    <i class="fa icon-email"></i><strong><label>email:</label> </strong><a href="#">demo@posthemes.com</a></p>
                </li>
                <li class="phone">
                    <i class="fa icon-phone"></i><strong><label>phone:</label> 0987.654.321</strong>
                </li>
            </ul>
        </div>
    </div>
</div>