<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>
<div class="language-box">
    <div class="language__inner-box">
        <a href="#" class="btn-current"><span>Language</span><i class="fa icon-arrow-down"></i></a>
        <ul class="dropdown-menu">
            <li><a href="#">Tiếng Việt</a></li>
            <li><a href="#">Tiếng Anh</a></li>
        </ul>
    </div>
</div>
