<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Currency switcher
 *
 * @see \Magento\Directory\Block\Currency
 */
?>
<div class="currencies-box">
    <div class="currencies__inner-box">
        <a href="#" class="btn-current"><i class="fa icon-usd" aria-hidden="true"></i>
        <span class="fa icon-arrow-down"></span></a>
        <ul class="dropdown-menu">
            <li><a href="#">VNĐ</a></li>
            <li><a href="#">Euro</a></li>
        </ul>
    </div>
</div>